version: "3"
services:
  db:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: traton
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./database-data/data:/db
  backend:
    links:
      - db
    depends_on:
      - db
    restart: on-failure
    env_file:
      - be/.env
    build: be
    ports:
      - "3001:3001"
  frontend:
    restart: on-failure
    build: fe
    ports:
      - "3000:3000"
